name: .NET Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.48.0-jammy

    steps:
      - uses: actions/checkout@v4

      - name: Restore project dependencies
        run: dotnet restore
        working-directory: Homework2.Tests/

      - name: Build project
        run: dotnet build --no-restore
        working-directory: Homework2.Tests/

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --settings Homework2.Tests/.runsettings
        working-directory: Homework2.Tests/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: Homework2.Tests/allure-results

  generate-report:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          destination_dir: allure